### ISSUE TITLE
Support PHP 8

### ISSUE THREAD

**Issue by webignition** [webignition/symfony-panther-dom-crawler-navigator#73]
- [x] webignition/web-driver-element-collection#21
- [x] webignition/php-dom-element-locator#15
- [x] webignition/php-dom-element-identifier#51
- [x] webignition/base-panther-test-case#31
